# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Prevents Travis timeout for building

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq

addons:
  apt:
  packages:
  - libtesseract-dev
  - libleptonica-dev
  - tesseract-ocr-eng
  - tesseract-ocr-por
  - libpoppler-cpp-dev
  - libxml2-dev

language: R
sudo: false
cache: packages
