# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

addons:
  apt:
  packages:
  - libtesseract-dev
- tesseract-ocr-eng
- tesseract-ocr-por
- libpoppler-cpp-dev
- libxml2-dev

language: R
sudo: false
cache: packages
